services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=recipe
      - POSTGRES_PASSWORD=RecipePassword
      - POSTGRES_DB=Recipe
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - 5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres:
  pgadmin-data: